---
- name: Install NFS server packages
  hosts: nfs-server
  become: true
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Install NFS server packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nfs-kernel-server

    - name: Ensure NFS server is running and enabled
      service:
        name: nfs-kernel-server
        state: started
        enabled: yes

    - name: Create a mountable directory if it does not exist
      file:
        path: /mnt/nfs_test
        state: directory
        owner: nobody
        group: nogroup
        mode: '0775'

    - name: Copy exports file.
      template:
        src: ./files/exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644

    - name: NFS apply change configrue
      shell: systemctl reload nfs;exportfs -a


